INSERT OR IGNORE INTO learn_resources (
  id,
  topic,
  title,
  url,
  type,
  description,
  added_by,
  added_by_name,
  is_active,
  created_at,
  updated_at
) VALUES
  (
    'seed-bonds-investor-corporate-bonds',
    'bonds',
    'Investor.gov: Corporate Bonds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/bonds-or-fixed-income-products',
    'article',
    'Beginner-friendly SEC overview of how corporate bonds work, including coupon payments, maturity, credit quality, and default risk.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-bonds-finra-bonds',
    'bonds',
    'FINRA: Bonds',
    'https://www.finra.org/investors/investing/investment-products/bonds',
    'article',
    'Practical bond guide covering bond types, pricing, yield, risks, and what to check before buying.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-bonds-treasury-savings-bonds',
    'bonds',
    'TreasuryDirect: U.S. Savings Bonds',
    'https://www.treasurydirect.gov/savings-bonds/',
    'article',
    'Official TreasuryDirect guide to EE bonds, I bonds, current rates, purchase limits, redemption rules, and inflation protection.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-bonds-finra-yield-return',
    'bonds',
    'FINRA: Understanding Bond Yield and Return',
    'https://www.finra.org/investors/insights/bond-yield-return',
    'article',
    'Practical explainer for coupon yield, current yield, yield to maturity, yield to call, and price-yield movement.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-stocks-investor-stocks',
    'stocks',
    'Investor.gov: Stocks',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks',
    'article',
    'SEC primer on what stocks are, why investors buy them, main stock categories, benefits, and risks.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-stocks-public-companies',
    'stocks',
    'Investor.gov: Public Companies',
    'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/public-companies',
    'article',
    'Useful guide to public company reporting, 10-Ks, 10-Qs, 8-Ks, proxy statements, and investor disclosures.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-stocks-researching-investments',
    'stocks',
    'Investor.gov: Researching Investments',
    'https://www.investor.gov/introduction-investing/getting-started/researching-investments',
    'article',
    'Due-diligence hub for checking filings, researching companies, and spotting unregistered or suspicious investments.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-stocks-sec-edgar-search',
    'stocks',
    'SEC EDGAR: Company Filing Search',
    'https://www.sec.gov/edgar/search/',
    'tool',
    'Official SEC search tool for public company filings, including annual reports, quarterly reports, and current reports.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-etfs-investor-etfs',
    'etfs-funds',
    'Investor.gov: Exchange-Traded Funds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-2',
    'article',
    'SEC guide to ETFs, including how they trade, how they differ from mutual funds, and what risks to review.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-etfs-investor-mutual-funds',
    'etfs-funds',
    'Investor.gov: Mutual Funds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-funds-etfs/mutual-funds',
    'article',
    'Beginner overview of mutual funds, diversification, fees, share classes, and investor protections.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-etfs-investor-index-funds',
    'etfs-funds',
    'Investor.gov: Index Funds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-4',
    'article',
    'Plain-language introduction to index funds and the tradeoffs of tracking an index instead of active selection.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-etfs-finra-etps',
    'etfs-funds',
    'FINRA: Exchange-Traded Funds and Products',
    'https://www.finra.org/investors/investing/investment-products/exchange-traded-funds-and-products',
    'article',
    'FINRA overview of ETFs, ETNs, trading mechanics, liquidity layers, costs, and specialized product risks.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-crypto-investor-crypto-assets',
    'crypto',
    'Investor.gov: Crypto Assets',
    'https://www.investor.gov/additional-resources/spotlight/crypto-assets',
    'article',
    'SEC resource hub for crypto assets, custody, exchange-traded products, scams, and investor questions.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-crypto-finra-crypto-assets',
    'crypto',
    'FINRA: Crypto Assets',
    'https://www.finra.org/investors/investing/investment-products/crypto-assets',
    'article',
    'FINRA guide explaining crypto asset types, buying and selling, volatility, custody, and key risks.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-crypto-custody-basics',
    'crypto',
    'Investor.gov: Crypto Custody Basics',
    'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/crypto-asset-custody-basics-retail-investors-investor-bulletin-0',
    'article',
    'SEC bulletin on private keys, seed phrases, hot and cold wallets, self-custody, and third-party custody risks.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-crypto-ftc-scams',
    'crypto',
    'FTC: Cryptocurrency and Scams',
    'https://consumer.ftc.gov/articles/what-know-about-cryptocurrency-scams',
    'article',
    'Consumer protection guide to common crypto scam patterns, payment red flags, and how to report fraud.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-venture-private-placements',
    'venture',
    'Investor.gov: Private Placements',
    'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/private',
    'article',
    'SEC bulletin on Regulation D private placements, limited disclosure, illiquidity, Form D, and red flags.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-venture-private-equity',
    'venture',
    'Investor.gov: Private Equity Funds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/private-investment-funds/private-equity',
    'article',
    'SEC overview of private equity funds, long holding periods, fees, conflicts, and who can usually invest.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-venture-accredited-investors',
    'venture',
    'Investor.gov: Accredited Investors',
    'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/updated-3',
    'article',
    'SEC bulletin explaining accredited investor rules and why many private deals are limited to certain investors.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-venture-hedge-funds',
    'venture',
    'Investor.gov: Hedge Funds',
    'https://www.investor.gov/introduction-investing/investing-basics/investment-products/private-investment-funds/hedge-funds',
    'article',
    'SEC guide to private funds, lockups, leverage, fees, manager research, and investor eligibility.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-cash-risk-asset-allocation',
    'cash-risk',
    'Investor.gov: Asset Allocation and Diversification',
    'https://www.investor.gov/introduction-investing/getting-started/asset-allocation',
    'article',
    'Core guide to spreading investments across asset classes and using diversification to manage risk.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-cash-risk-what-is-risk',
    'cash-risk',
    'Investor.gov: What Is Risk?',
    'https://www.investor.gov/introduction-investing/investing-basics/what-risk',
    'article',
    'Beginner explanation of investment risk, risk-return tradeoffs, inflation risk, liquidity risk, and market risk.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-cash-risk-risk-tolerance',
    'cash-risk',
    'Investor.gov: Gauge Your Risk Tolerance',
    'https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/gauge-your-risk-tolerance',
    'article',
    'Helpful framework for matching risk level to goals, time horizon, financial situation, and temperament.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  ),
  (
    'seed-cash-risk-fdic-deposit-insurance',
    'cash-risk',
    'FDIC: Deposit Insurance',
    'https://www.fdic.gov/resources/deposit-insurance',
    'article',
    'Official FDIC guide to what bank deposits are insured, what is not covered, and how coverage works.',
    NULL,
    'Lucrum editorial',
    1,
    '2026-06-13T00:00:00.000Z',
    '2026-06-13T00:00:00.000Z'
  );
